// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQV7Xq7iIEmk6FGfHn15epTpdDhuX0oM',
    appId: '1:278423559:web:cf6f9e881b8975aa96e2a2',
    messagingSenderId: '278423559',
    projectId: 'hot-deal-gene',
    authDomain: 'hot-deal-gene.firebaseapp.com',
    storageBucket: 'hot-deal-gene.appspot.com',
    measurementId: 'G-JXZ6XKCCHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkmb2AxD44T0cWmyo0pHuLZ1oE82YbbU',
    appId: '1:278423559:android:37d80e413eb3667996e2a2',
    messagingSenderId: '278423559',
    projectId: 'hot-deal-gene',
    storageBucket: 'hot-deal-gene.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMY1xIKpsLqzJKP05BTXMhiy0T9SLTEA',
    appId: '1:278423559:ios:c31ebc7c05d4d36b96e2a2',
    messagingSenderId: '278423559',
    projectId: 'hot-deal-gene',
    storageBucket: 'hot-deal-gene.appspot.com',
    iosBundleId: 'con.hotDeal.hotDealGeneration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlMY1xIKpsLqzJKP05BTXMhiy0T9SLTEA',
    appId: '1:278423559:ios:fcd973e4b505f73e96e2a2',
    messagingSenderId: '278423559',
    projectId: 'hot-deal-gene',
    storageBucket: 'hot-deal-gene.appspot.com',
    iosBundleId: 'con.hotDeal.hotDealGeneration.RunnerTests',
  );
}
